name: Security Analysis
on:
  pull_request:
    paths:
      - '**/*.py'
      - poetry.lock
  workflow_dispatch:

jobs:
  bandit:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Check Python version
        run: python --version

      - name: Install Poetry
        run: |
          curl -sSkL https://install.python-poetry.org | python -
          export PATH=$PATH:$HOME/.local/bin
          poetry --version
        env:
          POETRY_VERSION: ${{ vars.POETRY_VERSION }}

      - name: Install libgl1-mesa-dev
        run: |
          apt update
          apt -y install libgl1-mesa-dev
      
      - name: Install Dependencies
        run: |
          export PATH=$PATH:$HOME/.local/bin
          poetry install --only dev
      
      - name: Run Bandit
        run: |
          export PATH=$PATH:$HOME/.local/bin
          poetry run bandit -r .
