name: Static Analysis
on:
  pull_request:
  workflow_dispatch:

jobs:
  flake8:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Check Python version
        run: python --version

      - name: Install Poetry
        run: |
          export POETRY_VERSION=${{ vars.POETRY_VERSION }}
          curl -sSkL https://install.python-poetry.org | python -
          export PATH=$PATH:$HOME/.local/bin
          poetry --version

      - name: Install libgl1-mesa-dev
        run: |
          sudo apt update
          sudo apt -y install libgl1-mesa-dev

      - name: Install Dependencies
        run: poetry install --only dev

      - name: Run Flake8
        run: poetry run flake8 .

  black:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Check Python version
      run: python --version

    - name: Install Poetry
      run: |
        export POETRY_VERSION=${{ vars.POETRY_VERSION }}
        curl -sSkL https://install.python-poetry.org | python -
        export PATH=$PATH:$HOME/.local/bin
        poetry --version

    - name: Install libgl1-mesa-dev
      run: |
          sudo apt update
          sudo apt -y install libgl1-mesa-dev

    - name: Install Dependencies
      run: poetry install --only dev

    - name: Run Black
      run: poetry run black --check ./

  mypy:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Check Python version
        run: python --version

      - name: Install Poetry
        run: |
          export POETRY_VERSION=${{ vars.POETRY_VERSION }}
          curl -sSkL https://install.python-poetry.org | python -
          export PATH=$PATH:$HOME/.local/bin
          poetry --version

      - name: Install libgl1-mesa-dev
        run: |
          sudo apt update
          sudo apt -y install libgl1-mesa-dev

      - name: Install Dependencies
        run: poetry install --only dev

      - name: Run MyPy
        run: poetry run mypy --config-file pyproject.toml .

  isort:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Check Python version
        run: python --version

      - name: Install Poetry
        run: |
          export POETRY_VERSION=${{ vars.POETRY_VERSION }}
          curl -sSkL https://install.python-poetry.org | python -
          export PATH=$PATH:$HOME/.local/bin
          poetry --version

      - name: Install libgl1-mesa-dev
        run: |
          sudo apt update
          sudo apt -y install libgl1-mesa-dev

      - name: Install Dependencies
        run: poetry install --only dev

      - name: Run isort
        run: poetry run isort --check --profile black --trailing-comma -m=3 .
