name: GitHub Pages

on:
  pull_request:
  workflow_dispatch:

jobs:
  test-pages:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: actions/download-artifact@v3.0.2
      - name: Check Python version
        run: python --version

      - name: Install Poetry
        run: |
          curl -sSkL https://install.python-poetry.org | python -
          export PATH=$PATH:$HOME/.local/bin
          poetry --version
        env:
          POETRY_VERSION: ${{ vars.POETRY_VERSION }}

      - name: Install libgl1-mesa-dev
        run: |
          apt update
          apt -y install libgl1-mesa-dev

      - name: Install Dependencies
        run: |
          export PATH=$PATH:$HOME/.local/bin
          poetry install --only docs

      - name: Build Docs
        run: poetry run sphinx-build -d docs/build/doctrees docs/source docs/build/html

      - name: Move Docs
        run: mv docs/build/html public/

      - uses: actions/upload-artifact@v3.1.3
        if: success()
        with:
          name: "${{ github.job }}"
          retention-days: 7
          path: public/
